name: Destroy S3 bucket

on:
  workflow_dispatch:

jobs:
  terraform-actions:
    name: Destroy-S3-bucket
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: List текущий репозиторий files и мы можем совершать над ними действия
      run: ls -la

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.8

    - name: Terraform Init
      id: init
      run: terraform init
      continue-on-error: true

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      continue-on-error: true

    - name: Очистка s3 bucket от данных
      run: aws s3 rm s3://s3-website-html/ --recursive
    - name: List s3-website-html Bucket after
      run: aws s3 ls s3://s3-website-html
        
        
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Terraform Destroy
      id: Destroy
      run: terraform destroy -auto-approve -no-color
      continue-on-error: true
